# Generated by Django 3.2.5 on 2021-07-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='fonticon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
